### ISSUE TITLE
BottomCardListener is not public, cannot be set to BottomCardView from any view

### ISSUE THREAD

**Issue by astamato** [Mapwize/mapwize-ui-android#16]
As a user of Mapwize library, I'd like to inflate a custom version of BottomCardView, from a view that's not `MapwizeFragment`.
But `BottomCardView` layout component has public setter `setListener` receiving `BottomCardListener` which has default 'public/*package*/' accessibility. Therefore I cannot implement this listener at all from outside it's package.
On the contrary UIBehaviour is public and can be implemented no problem. 

More:
Getting java.lang.IllegalAccessError: Illegal class access: '{our class}' attempting to access 'io.mapwize.mapwizecomponents.ui.BottomCardView$BottomCardListener'

**Comment by emerciercontexeo** [comment]
I am not sure to understand what you want.

Do you want to have access to the BottomCardListener ? In this case, we can simply make it public.

Or do you want to be able to use a custom view for the BottomCardView ?

**Comment by astamato** [comment]
Yeah, just making the BottomCardListener interface public will do (:

**Comment by emerciercontexeo** [comment]
Ok. I don't have any reason to not make it public.

I can do it in the next release but, feel free to open a PR if you want it quickly :)

**Comment by emerciercontexeo** [comment]
Update done in 1.2.1
