### ISSUE TITLE
Possibility to set mapwize_main_color programmatically.

### ISSUE THREAD

**Issue by CodeFactoryPDabrowski** [Mapwize/mapwize-ui-android#17]
Currently, we can set mapwize main colour only by overriding this resource -> https://github.com/Mapwize/mapwize-ui-android/blob/master/app/src/main/res/values/colors.xml. On iOS side there is an option to set this colour from the code -> ` private var settings: MWZMapwizeViewUISettings {
        get {
            let settings = MWZMapwizeViewUISettings()
            settings.followUserButtonIsHidden = false
            settings.mainColor = Theme.primaryColor
            return settings
        }
    }`. Maybe it would be good to make this consistent? overriding colours has a disadvantage: what if the name of the colour will change? I as a user of the library shouldn't be worried about this :) Could you improve this? :)

**Comment by emerciercontexeo** [comment]
Hi,

I will work on an improvement for this but it requires an update in the MapwizeForMapbox plugin too.
I won't rush into this but I will do it as soon as I have some "free" time.

Thanks for reporting this point.

**Comment by CodeFactoryPDabrowski** [comment]
Hi, cool :D thanks for information :)
