### ISSUE TITLE
App crashes if mapview is destroyed already

### ISSUE THREAD

**Issue by lukacat10** [Mapwize/mapwize-ui-android#2]
When using mapwize in a "sub activity", and the activity is closed, before the places finished loading into the map, the app crashes stating:

E/Mbgl-NativeMapView: You're calling `getLayer` after the `MapView` was destroyed, were you invoking it after `onDestroy()`?
    You're calling `addImage` after the `MapView` was destroyed, were you invoking it after `onDestroy()`?
    You're calling `getLayer` after the `MapView` was destroyed, were you invoking it after `onDestroy()`?
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18 in tid 21828 (------), pid 21828 (-----)

Please provide an onDestroy method in the mapwize plugin, or check if the mapview is destroyed before trying to modify it.
I would try it myself but I couldn't find the mapwizeformapbox source code.
Thanks!

**Comment by emerciercontexeo** [comment]
Hi @lukacat10 ,

Thanks for reporting this issue.

I will update MapwizeForMapbox as soon as possible and publish a fixed version.

**Comment by lukacat10** [comment]
Hello. We used the latest version as well. Still crashes.

The reason why mapview's methods are called after its destroyed is probably because mapwize is still loading the data and trying to apply it after the mapview was destroyed.

You need to have to exit the activity before the the last layer loaded, but after it started loading the data (when the icon of the place mapwize supports showed up, but before it loaded all of the data related to this place).

So it's a specific state of loading when our users exit and crash their app.

All is needed is a way to block any access to mapview, and even better, stop any action done by mapwize, like loading info, so it doesn't run in the background and try stuff it can't do.

If you still can't produce it please write to me and I will work on a full example as soon as possible.

**Comment by lukacat10** [comment]
Oh wait, does 1.7.1 include the checks?

**Comment by emerciercontexeo** [comment]
@lukacat10 Yes, I added check in 1.7.1 of MapwizeForMapbox but, as I can't reproduce the bug at this moment, I can't be 100% sure about the fix.

I added mapview.isDestroyed check before all call of methods that interact with the map so, I believe in the fix.
