### ISSUE TITLE
UI should support MapwizeForMapbox v 2.3.2

### ISSUE THREAD

**Issue by CodeFactoryPDabrowski** [Mapwize/mapwize-ui-android#21]
Hi, 

MapwizeForMapbox v 2.3.0 was released with some breaking changes in methods **addMarker**. UI library(current version 1.3.1) is not updated to support the latest changes and when clicking on place then crash occurs. Could you update the ui library?

**Comment by emerciercontexeo** [comment]
Hi,

Thanks for reporting.

Done in 1.3.2.
