### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by devarshi1192** [Mapwize/mapwize-ui-android#32]
Hi Team,

I have configured a floor map on Mapwize.io with a trial version to test the feasibility as per my needs, but I am getting below error:

**E/io.mapwize.map: Error fetching venues: API_KEY Invalid**

I have tried resetting the key as well but still getting the same error. Are there some other steps as well other than adding key to MapwizeApplication.java file?

**Comment by m3ftah** [comment]
Hello,
No, You only need to change the `API_KEY` in the `MapwizeApplication.java` file, please check that your `API_KEY` has the right access permission to the venue(s) you are trying to show.

**Comment by m3ftah** [comment]
Hi,
I am closing this issue because it has been inactive for few months.

Please reopen if you still encounter this issue.

Thanks.
