### ISSUE TITLE
Map displaying bubbles for floors to the right even when there's only one floor

### ISSUE THREAD

**Issue by astamato** [Mapwize/mapwize-ui-android#4]
In the scenario of venue having only one floor, we'd like to be able to configure if the floor selector bubble should be visible or not.

**Comment by emerciercontexeo** [comment]
You can find an implementation here #10 

Let me know if it is ok for you.

**Comment by astamato** [comment]
Feature added in `com.github.Mapwize:mapwize-ui-android:1.0.2`, cheers!
