### ISSUE TITLE
Navigation will not update in real time

### ISSUE THREAD

**Issue by xanscale** [Mapwize/mapwize-ui-android#51]
**Describe the bug**
As documentation say, when start navigation from user position, UI (path, min/metres remaining) should update real time, seams not appen, only user location marker updates

**To Reproduce**
just start navigation from user position

**Expected behavior**
UI update in real time

**Smartphone (please complete the following information):**
all device we tested

**Versions (please complete the following information):**
 - `mapwize-ui-android` version: 2.4.1
 - `mapwize-sdk` version: 3.5.1

**Comment by m3ftah** [comment]
Hello,

Indeed, there is an issue with navigation, it has been resolved in the sdk version 3.5.2.

Thanks.
